kind: pipeline
type: docker
name: docker

steps:
  - name: install
    image: node:18
    commands:
      - curl -fsSL https://get.pnpm.io/install.sh | sh -
      - make install

  - name: ls-lint
    image: node:18
    commands:
      - make ls-lint

  - name: build
    image: node:18
    commands:
      - curl -fsSL https://get.pnpm.io/install.sh | sh -
      - make build