version: '3'

services:
  docs:
    image: registry.loeffel.io/ls-lint/docs:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/certs/server.crt:/usr/local/apache2/conf/server.crt
      - ~/certs/server.key:/usr/local/apache2/conf/server.key
    networks:
      - ls-lint-docs

networks:
  ls-lint-docs: